package DAO;

// SettingsDAO.java
// Handles database operations for the Settings screen, including
// adding and removing items and categories, retrieving the category
// list, and setting custom low-stock thresholds per restaurant.

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;

public class SettingsDAO {

    // Returns a list of all category names from the database.
    // "All" is added as the first entry so the inventory screen
    // can use it to mean "no category filter applied".
    public List<String> getCategories() {

        List<String> categories = new ArrayList<>();
        categories.add("All");

        String sql = "SELECT category_name FROM category ORDER BY category_name";

        try (Connection conn = DatabaseConnection.getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql);
             ResultSet rs = stmt.executeQuery())
        {
            while (rs.next()) {
                categories.add(rs.getString("category_name"));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

        return categories;
    }

    // Adds a new item to the item table.
    // Accepts human-readable names rather than raw database IDs,
    // so the user only needs to type the category name and unit abbreviation.
    // The method resolves those to their IDs internally before inserting.
    // All fields are required and the threshold must be a positive number.
    // Returns true if the insert succeeded, false otherwise.
    public boolean addItem(String itemName, String categoryName,
                           String unitAbbreviation, int lowStockThreshold) {

        // Validate all inputs before touching the database
        if (itemName == null || itemName.trim().isEmpty())                 return false;
        if (categoryName == null || categoryName.trim().isEmpty())         return false;
        if (unitAbbreviation == null || unitAbbreviation.trim().isEmpty()) return false;
        if (lowStockThreshold <= 0)                                        return false;

        String findCategorySql =
                "SELECT category_id FROM category WHERE category_name = ? LIMIT 1";
        String findUnitSql =
                "SELECT unit_id FROM unit WHERE unit_abbreviation = ? LIMIT 1";
        String insertItemSql =
                "INSERT INTO item " +
                        "(item_name, category_id, unit_id, is_active, create_date, low_stock_threshold) " +
                        "VALUES (?, ?, ?, TRUE, NOW(), ?)";

        try (Connection conn = DatabaseConnection.getConnection()) {

            // Step 1: Look up the category_id from the category name
            Integer categoryId = null;
            try (PreparedStatement catStmt = conn.prepareStatement(findCategorySql)) {
                catStmt.setString(1, categoryName.trim());
                try (ResultSet rs = catStmt.executeQuery()) {
                    if (rs.next()) categoryId = rs.getInt("category_id");
                }
            }
            if (categoryId == null) return false;   // Category not found in the database

            // Step 2: Look up the unit_id from the unit abbreviation
            Integer unitId = null;
            try (PreparedStatement unitStmt = conn.prepareStatement(findUnitSql)) {
                unitStmt.setString(1, unitAbbreviation.trim());
                try (ResultSet rs = unitStmt.executeQuery()) {
                    if (rs.next()) unitId = rs.getInt("unit_id");
                }
            }
            if (unitId == null) return false;   // Unit not found in the database

            // Step 3: Insert the new item; the item_id is auto-generated by MySQL
            try (PreparedStatement insertStmt = conn.prepareStatement(insertItemSql)) {
                insertStmt.setString(1, itemName.trim());
                insertStmt.setInt(2, categoryId);
                insertStmt.setInt(3, unitId);
                insertStmt.setInt(4, lowStockThreshold);
                insertStmt.executeUpdate();
            }

            return true;

        } catch (Exception e) {
            e.printStackTrace();
            return false;
        }
    }

    // Soft-deletes an item by setting its is_active flag to FALSE.
    // The item will no longer appear on any screen, but all of its
    // transaction history remains intact in the database.
    // Returns true if the item was found and deactivated, false otherwise.
    public boolean deactivateItem(String itemName) {

        if (itemName == null || itemName.trim().isEmpty()) return false;

        String sql =
                "UPDATE item SET is_active = FALSE " +
                        "WHERE item_name = ? AND is_active = TRUE";

        try (Connection conn = DatabaseConnection.getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql))
        {
            stmt.setString(1, itemName.trim());
            int rows = stmt.executeUpdate();
            return rows > 0;   // returns false if the item was not found

        } catch (Exception e) {
            e.printStackTrace();
            return false;
        }
    }

    // Inserts a new category into the category table.
    // Returns true on success. Will return false if the name already exists
    // due to the UNIQUE constraint on category_name.
    public boolean addCategory(String categoryName) {

        if (categoryName == null || categoryName.trim().isEmpty()) return false;

        String sql = "INSERT INTO category (category_name) VALUES (?)";

        try (Connection conn = DatabaseConnection.getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql))
        {
            stmt.setString(1, categoryName.trim());
            stmt.executeUpdate();
            return true;

        } catch (Exception e) {
            e.printStackTrace();
            return false;
        }
    }

    // Deletes a category from the database.
    // This will fail if any active items still belong to this category
    // because of the foreign key constraint, which is the intended behaviour.
    // Returns true if the category was deleted, false otherwise.
    public boolean removeCategory(String categoryName) {

        if (categoryName == null || categoryName.trim().isEmpty()) return false;

        String sql = "DELETE FROM category WHERE category_name = ?";

        try (Connection conn = DatabaseConnection.getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql))
        {
            stmt.setString(1, categoryName.trim());
            int rows = stmt.executeUpdate();
            return rows > 0;

        } catch (Exception e) {
            e.printStackTrace();
            return false;
        }
    }

    // Sets a custom low-stock threshold for a specific item at a specific restaurant.
    // This overrides the global threshold stored on the item for this restaurant only.
    // If no inventory row exists yet for this restaurant and item, one is created
    // automatically with a quantity of zero.
    // Returns true on success, false if the item is not found or something goes wrong.
    public boolean setLowStockThresholdOverride(int restaurantId,
                                                String itemName,
                                                int newThreshold) {

        // Validate inputs before making any database calls
        if (restaurantId <= 0)                             return false;
        if (itemName == null || itemName.trim().isEmpty()) return false;
        if (newThreshold <= 0)                             return false;

        String findItemSql =
                "SELECT item_id FROM item " +
                        "WHERE item_name = ? AND is_active = TRUE LIMIT 1";

        String updateInventorySql =
                "UPDATE inventory " +
                        "SET min_quantity_override = ? " +
                        "WHERE restaurant_id = ? AND item_id = ?";

        // If no inventory row exists for this restaurant and item, create one
        String insertInventorySql =
                "INSERT INTO inventory " +
                        "(restaurant_id, item_id, quantity_on_hand, quantity_reserved, min_quantity_override) " +
                        "VALUES (?, ?, 0, 0, ?)";

        try (Connection conn = DatabaseConnection.getConnection()) {

            // Step 1: Get the item_id from the item name
            Integer itemId = null;
            try (PreparedStatement findStmt = conn.prepareStatement(findItemSql)) {
                findStmt.setString(1, itemName.trim());
                try (ResultSet rs = findStmt.executeQuery()) {
                    if (rs.next()) itemId = rs.getInt("item_id");
                }
            }
            if (itemId == null) return false;   // Item not found

            // Step 2: Try to update the existing inventory row
            int updatedRows;
            try (PreparedStatement updateStmt = conn.prepareStatement(updateInventorySql)) {
                updateStmt.setInt(1, newThreshold);
                updateStmt.setInt(2, restaurantId);
                updateStmt.setInt(3, itemId);
                updatedRows = updateStmt.executeUpdate();
            }

            // Step 3: If no row was updated, the inventory row does not exist yet, so insert it
            if (updatedRows == 0) {
                try (PreparedStatement insertStmt = conn.prepareStatement(insertInventorySql)) {
                    insertStmt.setInt(1, restaurantId);
                    insertStmt.setInt(2, itemId);
                    insertStmt.setInt(3, newThreshold);
                    insertStmt.executeUpdate();
                }
            }

            return true;

        } catch (Exception e) {
            e.printStackTrace();
            return false;
        }
    }
}
